### ISSUE TITLE
Using with QEMU

### ISSUE THREAD

**Issue by ricardojlrufino** [romainreignier/minimal_raspberrypi_buildroot#4]
Is it possible to run this image in QEMU?

I get this error:
![image](https://user-images.githubusercontent.com/515675/112778105-276df880-901a-11eb-8321-8a60c02dc692.png)

Using QEMU 5.2

```
qemu-system-arm \
  -M versatilepb \
  -cpu arm1176 \
  -m 256 \
  -drive "file=$BUILD_RPI/sdcard.img,if=none,index=0,media=disk,format=raw,id=disk0" \
  -device "virtio-blk-pci,drive=disk0,disable-modern=on,disable-legacy=off" \
  -net user,hostfwd=tcp::10022-:22 \
  -net nic \
  -dtb $BUILD_RPI/rpi/versatile-pb-buster-5.4.51.dtb \
  -kernel $BUILD_RPI/rpi/kernel-qemu-5.4.51-buster \
  -append 'rootwait root=/dev/vda2' \
  -no-reboot
```

**Comment by romainreignier** [comment]
Hi @ricardojlrufino 
This system does not support QEMU boot. It has been optimized for the Raspberry Pi hardware. Some modules must be missing to be used in a Virtual Machine.
